//
import "./globals.css";

//
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: { icon: "/favicon.ico" },
  title: {
    default: "Garage",
    template: "%sGarage",
  },
  viewport: {
    initialScale: 1,
    width: "device-width",
  },
};
const roboto = Roboto({
  subsets: ["cyrillic", "cyrillic-ext", "latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});
const RootLayout: React.Layout = ({ children }) => {
  return (
    <html className={roboto.className} lang="en">
      <body className="bg-gray-100">{children}</body>
    </html>
  );
};
export default RootLayout;
